CREATE DATABASE IF NOT EXISTS CineBase 
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

USE CineBase;



CREATE TABLE IF NOT EXISTS t_Country (
	ID SERIAL PRIMARY KEY,
    Country VARCHAR(150) NOT NULL,
    UNIQUE uk_Country (Country)
);
CREATE TABLE IF NOT EXISTS t_City (
	ID SERIAL PRIMARY KEY,
	Postalcode VARCHAR(10) NOT NULL,
    City VARCHAR (250) NOT NULL,
    CountryID BIGINT UNSIGNED NOT NULL,
	CONSTRAINT fk_CityCountry FOREIGN KEY (CountryID) REFERENCES t_Country(ID),
    UNIQUE uk_CityPostCountry (Postalcode, City, CountryID)
);
CREATE TABLE IF NOT EXISTS t_Address (
	ID SERIAL PRIMARY KEY,
    Street VARCHAR(250) NOT NULL,
    StrNr SMALLINT UNSIGNED NOT NULL,
    CityID BIGINT UNSIGNED NOT NULL,
    CONSTRAINT fk_AddressCity FOREIGN KEY (CityID) REFERENCES t_City(ID)
);
CREATE TABLE IF NOT EXISTS t_Cinema(
	ID SERIAL PRIMARY KEY,
    CineName VARCHAR (100) NOT NULL,
    AddressID BIGINT UNSIGNED NOT NULL,
    Tel VARCHAR(25) NOT NULL,
    CONSTRAINT fk_CineAddress FOREIGN KEY (AddressID) REFERENCES t_Address(ID),
    UNIQUE uk_CinemaAddress (AddressID)
);

CREATE TABLE IF NOT EXISTS t_Hall(
	ID SERIAL PRIMARY KEY,
    CinemaID BIGINT UNSIGNED NOT NULL,
    HallName VARCHAR(50) NOT NULL,
    CONSTRAINT fk_CinemaHall FOREIGN KEY (CinemaID) REFERENCES t_Cinema(ID),
    UNIQUE uk_CinemaHall (HallName, CinemaID)
);

CREATE TABLE IF NOT EXISTS t_Seat(
	ID SERIAL PRIMARY KEY,
    HallID BIGINT UNSIGNED NOT NULL,
    Rownumber INT UNSIGNED NOT NULL,
    CellNumber INT UNSIGNED NOT NULL,
    CONSTRAINT fk_HallSeat FOREIGN KEY (HallID) REFERENCES t_Hall(ID),
    UNIQUE uk_HallRowCell (Rownumber, CellNumber, HallID)
);

CREATE TABLE IF NOT EXISTS t_Movie (
	ID SERIAL PRIMARY KEY,
    Name VARCHAR(150) NOT NULL,
    Description TEXT,
    Duration DATETIME NOT NULL,
    Price Decimal(3,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS t_MoviePerformence (
	ID SERIAL PRIMARY KEY,
    MovieID BIGINT UNSIGNED NOT NULL,
    HallID BIGINT UNSIGNED NOT NULL,
    StartTime DATETIME NOT NULL,
    CONSTRAINT fk_PerfMovie FOREIGN KEY (MovieID) REFERENCES t_Movie(ID),
    CONSTRAINT fk_PerfHall FOREIGN KEY (HallID) REFERENCES t_Hall(ID),
    UNIQUE uk_MoviePerformence (MovieID, HallID, StartTime)
);

CREATE TABLE IF NOT EXISTS t_BaseAcount (
	ID SERIAL PRIMARY KEY,
    Username VARCHAR (30) NOT NULL,
    Pass VARCHAR(500) NOT NULL,
    FirstName VARCHAR (100) NOT NULL,
    LastName VARCHAR (100) NOT NULL,
    UNIQUE uk_Username (Username)
);

CREATE TABLE IF NOT EXISTS t_User (
	ID BIGINT UNSIGNED PRIMARY KEY,
    MailAddress VARCHAR(100) NOT NULL,
    AddressID BIGINT UNSIGNED NOT NULL,
    CONSTRAINT fk_UserAccount FOREIGN KEY (ID) REFERENCES t_BaseAcount(ID),
    CONSTRAINT fk_UserAddress FOREIGN KEY (AddressID) REFERENCES t_Address(ID),
    UNIQUE uk_UserAddress (AddressID),
    UNIQUE uk_MailAddt_Countryress (MailAddress)
);

CREATE TABLE IF NOT EXISTS t_Manager (
	ID BIGINT UNSIGNED UNIQUE NOT NULL PRIMARY KEY,
    CONSTRAINT fk_ManagerAccount FOREIGN KEY (ID) REFERENCES t_BaseAcount(ID)
);

CREATE TABLE IF NOT EXISTS t_Cashier (
	ID BIGINT UNSIGNED UNIQUE NOT NULL PRIMARY KEY,
    CinemaID BIGINT UNSIGNED NOT NULL,
    CONSTRAINT fk_CashierAccount FOREIGN KEY (ID) REFERENCES t_BaseAcount(ID),
    CONSTRAINT fk_CashierCinema FOREIGN KEY (CinemaID) REFERENCES t_Cinema(ID)
);

CREATE TABLE IF NOT EXISTS t_Ticket (
	ID SERIAL PRIMARY KEY,
    PerformenceID BIGINT UNSIGNED NOT NULL,
    SeatID BIGINT UNSIGNED NOT NULL,
    SoldDate Date,
    UserID BIGINT UNSIGNED NOT NULL,
    CONSTRAINT fk_PerfTicket FOREIGN KEY (PerformenceID) REFERENCES t_MoviePerformence(ID),
    CONSTRAINT fk_TicketSeat FOREIGN KEY (SeatID) REFERENCES t_Seat(ID),
    CONSTRAINT fk_TicketUser FOREIGN KEY (UserID) REFERENCES t_User(ID),
    UNIQUE uk_Ticket (PerformenceID, SeatID)
);